---
name: nfsstack
services:
  busy:
    image: busybox:1.36
    container_name: busynfs
    command:
      - sleep
      - "3600"
    volumes:
      - datanfs:/partage

volumes:
  datanfs:
    driver_opts:
      type: nfs
      o: addr=192.168.56.200,vers=4
      device: ":/html"
