---
name: busystack
services:
  busysvc:
    image: busybox:1.36
    container_name: busy
    hostname: busycnt
    volumes:
      - data:/partage
      - /home/stagiaire/data:/data
    networks:
      busynet:
        ipv4_address: 172.20.0.100
    ports:
      - 80:80
    environment:
      - STAGE=DOCKER
    restart: unless-stopped
    command: sleep 3600

volumes:
  data:

networks:
  busynet:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.255.254
    driver_opts:
      com.docker.network.bridge.name: busynet0
