---
name: traefik
services:
  proxy:
    image: traefik:v3.6
    container_name: proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
    networks:
      proxynet:

networks:
  proxynet:
    name: proxynet
    driver_opts:
      com.docker.network.bridge.name: proxynet0
