---
x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 5

name: lemp-proxy
services:
  www:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: www
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_PREFIX}.${NGINX_IPV4}
      proxynet:
    # ports:
    #   - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-conf:/etc/nginx/conf.d/
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.routers.www.rule=Host(`www.stage.local`)
    <<: *default-logging

  php:
    image: ${PHP_IMAGE}:${PHP_IMAGE_TAG}
    build:
      context: ../03_dockerfile/
      dockerfile: Dockerfile
    container_name: php
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_PREFIX}.${PHP_IPV4}
    volumes:
      - ./html:/var/www/html
    restart: unless-stopped
    <<: *default-logging

  db:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: mariadb
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_PREFIX}.${MARIADB_IPV4}
    volumes:
      - datadb:/var/lib/mysql
    restart: unless-stopped
    # env_file: ./mariadb.env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PWD}
    <<: *default-logging

volumes:
  datadb:

networks:
  lempnet:
    ipam:
      config:
        - subnet: ${LEMPNET_PREFIX}.0.0/16
          gateway: ${LEMPNET_PREFIX}.255.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0
  proxynet:
    external: true
