---
name: whostack
services:
  who-1:
    image: traefik/whoami
    container_name: who-1
    hostname: who-1
    restart: unless-stopped
    ports:
      - 8081:80

  who-2:
    image: traefik/whoami
    container_name: who-2
    hostname: who-2
    restart: unless-stopped
    ports:
      - 8082:80

  who-3:
    image: traefik/whoami
    container_name: who-3
    hostname: who-3
    restart: unless-stopped
    ports:
      - 8083:80
